# Change these first
owner: AkashRajpurohit # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AkashRajpurohit
    url: https://akashrajpurohit.com
  - name: Umami (Cloud)
    url: https://tanjiro.akashrajpurohit.com
  # - name: Umami (Self-Hosted)
  #   url: https://rengoku.akashrajpurohit.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "FindingAkash"
  commitAuthorEmail: "bot@akashrajpurohit.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
